version: '3'


services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "verystrong!pass123"
      MSSQL_PID: Express
    volumes:
      - pgbsnh20-ex2:/var/opt/mssql
volumes:
  pgbsnh20-ex2:
    driver: local